# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-06 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_current_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='priority',
            field=models.CharField(default='medium', max_length=10),
        ),
    ]
