# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-04 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_member_checks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='checks',
        ),
    ]
