# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-04 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160415_1824'),
        ('accounts', '0008_remove_member_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='checks',
            field=models.ManyToManyField(to='api.Check'),
        ),
    ]
