# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-09 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180709_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team_priority',
            field=models.CharField(default='medium', max_length=12),
        ),
    ]
