# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-09 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_team_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='team_priority',
        ),
        migrations.AddField(
            model_name='member',
            name='team_priority',
            field=models.CharField(default='medium', max_length=12),
        ),
    ]
