# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-12 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180709_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='team_priority',
            field=models.BooleanField(default='False', max_length=12),
        ),
    ]
