# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180712_1304'),
        ('accounts', '0009_member_checks'),
    ]

    operations = [
    ]
