# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_merge_20180716_0947'),
        ('accounts', '0015_merge_20180717_0921'),
    ]

    operations = [
    ]
