# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-09 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160415_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='member_check_priority',
            field=models.CharField(default='medium', max_length=12),
        ),
    ]
