# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_check_member_check_priority'),
        ('api', '0028_auto_20180706_0945'),
    ]

    operations = [
    ]
