# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-12 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_check_member_check_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='alert_stay_down',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
