# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_merge_20180716_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='alert_stay_down',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='kind',
            field=models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook'), ('hipchat', 'HipChat'), ('slack', 'Slack'), ('pd', 'PagerDuty'), ('po', 'Pushover'), ('victorops', 'VictorOps'), ('sms', 'SMS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('new', 'New'), ('paused', 'Paused'), ('nag', 'Nag'), ('down-ext', 'Down-ext')], default='new', max_length=9),
        ),
        migrations.AlterField(
            model_name='notification',
            name='check_status',
            field=models.CharField(max_length=9),
        ),
    ]
