# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-12 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_check_alert_stay_down'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('new', 'New'), ('paused', 'Paused'), ('down-ext', 'Down-Ext')], default='new', max_length=9),
        ),
    ]
