# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180716_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='alert_stay_down',
        ),
    ]
