# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-12 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180712_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='check_status',
            field=models.CharField(max_length=9),
        ),
    ]
