# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_check_alert_stay_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='alert_stay_down',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
