# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180717_1004'),
        ('api', '0032_check_alert_stay_down'),
    ]

    operations = [
    ]
